### ISSUE TITLE
does not build on ubuntu xenial 16.04 lts (log included)

### ISSUE THREAD

**Issue by mailinglists35** [tinuzz/scst-3.x-debian#2]
Hello,
I tried building on latest git master but it fails. Filed the issue below.
Do you have any hint what could be the cause? running manually `make scst iscsi` works ok

https://github.com/bvanassche/scst/issues/7

Thank you!

**Comment by mailinglists35** [comment]
@tinuzz , on the issue I raised on scst github repo, [@bvanassche suggested](https://github.com/bvanassche/scst/issues/7#issuecomment-278551493) using master branch instead of 3.1.
Could you adjust the files to make it build on master?

**Comment by tinuzz** [comment]
Hi,

I am sorry, I don't really have the time. I do SCST upgrades VERY infrequently (at most once a year), because the impact on my environment is gigantic. Any issues I encounter at that time, I will fix in this repo, but besides that, there's not much I can do. Also, this is ONLY done on Debian Stable and not on any other OS, like Ubuntu Xenial nor any other flavour of Debian. Sorry about that.

Best regards,
Martijn.
